titlebar // thanh tiêu đề;
style: stīl // phong cách;
default: dəˈfôlt // mặc định;
resize: // thay đổi kích thước;
state: stāt // tình trạng;
screen: skrēn // màn hình;
create: krēˈāt// tạo nên;
program: //chương trình;
event:// sự kiện;
since the last:// kể từ lần cuối;
loop:// lặp
triggered: // kích hoạt
optional:  // ko bắt buộc;
requensted; // đóng;
joystick: // cần điều khiển;
move: //di chuyển;
mouse: // chuột;
process: // quá trình;
terminated: // chấm dứt;
status:// trạng thái;
key pressed:// nhấn phím;
keyboard: // bàn phím;
graphics: // đồ họa;
audio: // âm thanh;
network: // mạng;
real: // thực tế;
conole: kənˈsōl// bảng điều khiển;
character: // tính cách;
shape: // hình dạng;
circle: // vòng tròn;
set fill color: // đặt màu tô;
set position: // đặt vị trí;
cilre shape character: // nhân vật hình tròn;
green: // màu xanh lá;
poll event: //thăm dò ý kiến;
left: // hướng trái;
right: // Hướng phải;
up: // hướng lên;
down: // hướng xuống;
name space: // ko gian tên;
get axis position: // lấy vị trí trục;
enumeration: // sự liệt kê;
scancode: // quét mã;
scope: // phạm vi;
declared: dəˈklerd// tuyên bố, khai báo;
did you mean: mēn// ý bạn là;
member: //thành viên;
token: // thông báo;
library; // thư viện;
Enable: // cho phép;
context: // bối cảnh;
context settings: // ngữ cảnh;
draw: drô // vẽ tranh;
sprite: // đồ họa máy tính;
entity: ˈen(t)ədē // thực thể;
rectangle: ˈrekˌtaNGɡ(ə)l // hình chữ nhật;
texture: ˈtek(st)SHər // kết cấu;
memory: // ký ức;
declared in this scope: // được khai báo trong phạm vi này
triangle: // hinh tam giac;
intrect: // gián tiếp;
int rect: // trực tiếp;
rotation: rōˈtāSHən // sự xoay vòng;
get rotation: // thiết lập vòng xoay;
absolute: ˈabsəˌlo͞ot// tuyệt đối;
absolute position: //vị trí tuyệt đối;
absptule angle: // góc tuyệt đối;
scale: skāl // tỉ lệ;
factor: ˈfaktər// nhân tố// hệ số
absolute scale factor: //hệ số tỉ lệ tuyệt đối;
between: bəˈtwēn // giữa;
control; // điều khiển;
attribute: // thuộc tính;
method: // phương thức, phương pháp;
abstraction: // sự trừu tượng;
encapsulation: inˌkaps(y)əˈlāSH(ə)n // tính đóng gói;
private: // riêng tư;
inheritance: inˈherəd(ə)ns// tính kế thừa;
polymorphism:ˌpälēˈmôrˌfiz(ə)m // tính đa hình;
within: // ở trong;
move: // di chuyển;
global: // toàn cầu;
bound: // ràng buộc;
bounds: // giới hạn;
intersects: // giao nhau;
collision: kəˈliZH(ə)n// va chạm;
convert: // chuyển đổi;
could: ko͝od// có thể;
width: // chiều rộng;
height: // chiều cao;
front: // đằng trước;
coordinates: // tạo độ
distance; ˈdist(ə)ns // khoang cach;
set the: // thiết lập;
ate: // anw roif;
improve: // cải thiện;
scale: skāl // tỉ lệ;
replay: // chơi lại, diễn lại, làm lại;
simple: // đơn giản;
any: // bất kì;
other: // khác;
entity: ˈen(t)ədē// thực thể;
rotate: // quay;
degrees: // độ;
array: // mảng;
antialiasing: ˌanˌtīˈālēəsiNG// khử răng cưa;
frame:  // khung;
cylindrical: səˈlindrik(ə)l// hình trụ;
resize: // thay ddooir kcihs thuocws;
as seconds: // tính bằng giây;
get elapsed time: // lấy thời gian;
square: skwer // quảng trường;
square shape: // hình vuông;
triangular: trīˈaNGɡyələr // hình tam giác;
arrange: əˈrānj // xắp xếp;
object touches the ground: // vật chạm đất;
straight line: // thẳng hàng;
erase: // xóa;
